name: chat
recipe: laravel
config:
  webroot: ./public
services:
  node:
    type: node:20
    scanner: false
    ports:
      - 3009:3009
    build:
      - npm install
tooling:
  node:
    service: node
    cmd: node
  npm:
    service: node
    cmd: npm
  npx:
    service: node
    cmd: npx
    